version: '3.6'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gophoter
      POSTGRES_HOST: postgres
      #POSTGRES_URL: postgres://admin:password@localhost:5432/gophoter
    ports:
      - "5432:5432"
  gophoter-api:
    build: ./
    working_dir: /home/node/gophoter-api
    environment:
      POSTGRES_URL: postgres://admin:password@localhost:5432/gophoter
    links:
      - postgres
    ports: 
      - "3000:3000"
    volumes:
      - ../:/home/node/gophoter-api
    depends_on:
      - postgres
      
